#!/bin/sh

set -e
cd "$(dirname "$0")/.."

if [ "$1" = "prod" ]
then
    S3_BUCKET="s3://drk-barmbek.de"
    CF_DISTRIBUTION="E15XZP3ZYCIBZY"
else
    S3_BUCKET="s3://beta.drk-barmbek.de"
    CF_DISTRIBUTION="EA6Z498YNW5GA"
fi

npm run build
aws s3 sync  --delete  build/ "$S3_BUCKET"
aws cloudfront create-invalidation --distribution-id "$CF_DISTRIBUTION" --paths '/*'
